chore: contextualize models attributes
leroy-merlin-br/mongolid pull request #223
Opened 2023-10-18 17:57 UTC by gabrielgomes94

This PR contextualize attributes traits and interfaces inside a directory on `src/Model/Attributes/` and `tests/Unit/Model/Attributes`.

2023-10-18 18:03 UTC, ezandonai submitted a review, later dismissed

2023-10-19 13:16 UTC, ezandonai approved these changes

2023-10-19 14:56 UTC, williancs requested changes

2023-10-19 14:56 UTC, williancs commented on src/Model/Attributes/HasAttributesInterface.php
> +namespace Mongolid\Model\Attributes;
This can cause breaking change.
Are we going to upload the version?

2023-10-19 17:21 UTC, gabrielgomes94 commented on src/Model/Attributes/HasAttributesInterface.php
> +namespace Mongolid\Model\Attributes;
Nice observation. I was not taking into consideration that projects could or would use this Interface. 

Its better to leave this kind of alteration for mongolid 4.0 indeed.

2023-10-19 17:25 UTC, closed without merging

2023-10-19 17:25 UTC, gabrielgomes94 commented
Change interface namespaces could break compability with our clients. Its better to leave this kind of change for a version upload as said by @williancs